// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1R4kULuKaimLPEilJ5N8aUnqGIhJShSY',
    appId: '1:970283442139:web:ed94bbef55b65377ab51fe',
    messagingSenderId: '970283442139',
    projectId: 'arjun-guruji-app-d6da1',
    authDomain: 'arjun-guruji-app-d6da1.firebaseapp.com',
    storageBucket: 'arjun-guruji-app-d6da1.firebasestorage.app',
    measurementId: 'G-6J9DTKTL4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGsJWH4U91GZdXxBKESJZ5veToJWa5C70',
    appId: '1:970283442139:android:b97ca92242d8262bab51fe',
    messagingSenderId: '970283442139',
    projectId: 'arjun-guruji-app-d6da1',
    storageBucket: 'arjun-guruji-app-d6da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcL3AW_0DVZiAthf-DAD01V-YlMVM-qoc',
    appId: '1:970283442139:ios:568bde77bf1cc541ab51fe',
    messagingSenderId: '970283442139',
    projectId: 'arjun-guruji-app-d6da1',
    storageBucket: 'arjun-guruji-app-d6da1.firebasestorage.app',
    iosBundleId: 'com.example.arjunGuruji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcL3AW_0DVZiAthf-DAD01V-YlMVM-qoc',
    appId: '1:970283442139:ios:568bde77bf1cc541ab51fe',
    messagingSenderId: '970283442139',
    projectId: 'arjun-guruji-app-d6da1',
    storageBucket: 'arjun-guruji-app-d6da1.firebasestorage.app',
    iosBundleId: 'com.example.arjunGuruji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1R4kULuKaimLPEilJ5N8aUnqGIhJShSY',
    appId: '1:970283442139:web:203a846fb205a527ab51fe',
    messagingSenderId: '970283442139',
    projectId: 'arjun-guruji-app-d6da1',
    authDomain: 'arjun-guruji-app-d6da1.firebaseapp.com',
    storageBucket: 'arjun-guruji-app-d6da1.firebasestorage.app',
    measurementId: 'G-C3Z881F0MS',
  );
}